name: Bedrock Node.js CI

on: [push]

jobs:
  test-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    #needs: [lint]
    services:
      mongodb:
        image: mongo:4.2
        ports:
          - 27017:27017
    strategy:
      matrix:
        #node-version: [12.x, 14.x]
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd test
        npm install
    - name: Run test with Node.js ${{ matrix.node-version }}
      env:
        # Used to create a unique database name extension.
        # See test/test.config.js.
        TEST_NODE_VERSION: ${{ matrix.node-version }}
      run: |
        cd test
        npm test
#  lint:
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    strategy:
#      matrix:
#        node-version: [14.x]
#    steps:
#    - uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - run: npm install
#    - name: Run eslint
#      run: npm run lint
#  coverage:
#    needs: [test-node]
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    services:
#      mongodb:
#        image: mongo:4.2
#        ports:
#          - 27017:27017
#    strategy:
#      matrix:
#        node-version: [14.x]
#    steps:
#    - uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - run: |
#        cd test
#        npm install
#    - name: Generate coverage report
#      run: |
#        cd test
#        npm run coverage-ci
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        file: ./test/coverage/lcov.info
#        fail_ci_if_error: true
